### ISSUE TITLE
[REQUEST] Plugins and settings

### ISSUE THREAD

**Issue by marcemira** [froala/ember-froala#1]
Please add support for plugin settings at ember-cli-build.js. i.e:

``` javascript
var app = new EmberApp(defaults, {
...
  emberFroala: {
    fontAwesome: true,
    theme: 'gray',
    lang: 'en_us',
    plugins: [
      'block_styles',
      'char_counter', 
      'colors', 'entities',
      'file_upload',
      'font_family',
      'font_size',
      'fullscreen',
      'inline_styles',
      'lists',
      'media_manager',
      'tables',
      'urls',
      'video'
    ]
  }
...
});
```

Thanks!

**Comment by stefanneculai** [comment]
@maulsea @jigneshchudasama05 any thoughts about this one? Thanks!

**Comment by maulsea** [comment]
@stefanneculai Yeah, this does sound like a good idea. Sorry, I'm away for few days. Let me have a closer look once I'm back. Thanks!

**Comment by stefanneculai** [comment]
@maulsea any news? Thanks!

**Comment by kmmathis** [comment]
I'm definitely looking for this as well. I mostly need an option to stop the add-on from including Font Awesome, as I've already included it in my stylesheet with Sass.

**Comment by marcemira** [comment]
:+1: anyone?

**Comment by artsmc** [comment]
Currently testing!

**Comment by artsmc** [comment]
Going to update the readMe doc but this is now possible.
