### ISSUE TITLE
[REQUEST] Way to add new buttons

### ISSUE THREAD

**Issue by drapergeek** [froala/ember-froala#13]
Do you all have a recommended way to add custom buttons or dropdowns? My current idea is to inherit from your base component and add these on there but that seems less than ideal and I was hoping there may be some easier way.

**Comment by artsmc** [comment]
When you say add custom buttons or dropdowns are you referring to buttons inside the froala editor?
or would this be functionality outside of the editor ex. custom save button

**Comment by drapergeek** [comment]
Yes - https://www.froala.com/wysiwyg-editor/docs/concepts/custom-dropdown

**Comment by artsmc** [comment]
Got, think I will spend some time today on documenting more concepts. And determining if their are better ways to execute them inside ember.

https://www.froala.com/wysiwyg-editor/docs/concepts/custom-button
The base component creates a class for the froalaEditor object so you always have access to it.
In your component you would just define the icon using the class name.
~~$('.froalaEditor').DefineIcon('alert', {NAME: 'info'});~~
I take that back. that test will fail, I will add this feature to the plugin.

**Comment by drapergeek** [comment]
I've started playing with it and it seems that the best option (so far) would be to use an initializer to set up the custom things we need. Then I can just choose those options for the editor params.

**Comment by artsmc** [comment]
There is another request to have plugins and settings (options) inside, ember-cli-build.js
So the question becomes where to put what so it makes sense and everyone is playing nice together.

**Comment by artsmc** [comment]
@drapergeek  I'm curious as to how you used the initializer. At the moment I'm inclined to keep things inside the component just to have a single source of truth.

```
froalaEditor: {
    params: {},
    buttons:[]
}
```

Then you would just register a button inside a function in the array so something like:
**the template**

```
{{froala-editor customButtons=froalaEditor.buttons params=froalaEditor.params  }}
```

**the component**

```
froalaEditor: {
        params: {
        toolbarButtons: ['my_dropdown'],
        },
        buttons:[function(){
            $.FroalaEditor.DefineIcon('my_dropdown', {NAME: 'cog'});
            $.FroalaEditor.RegisterCommand('my_dropdown', {
              title: 'Advanced options',
              type: 'dropdown',
              focus: false,
              undo: false,
              refreshAfterCallback: true,
              options: {
                'v1': 'Option 1',
                'v2': 'Option 2'
              },
              callback: function (cmd, val) {
                console.log (val);
              },
              // Callback on refresh.
              refresh: function ($btn) {
                console.log ('do refresh');
              },
              // Callback on dropdown show.
              refreshOnShow: function ($btn, $dropdown) {
                console.log ('do refresh when show');
              }
            });
        }]
}
```

**Comment by drapergeek** [comment]
@artsmc I agree, I think I prefer your solution as well.  My initializer done the same basic thing but it was operating a global level which is less than ideal.

**Comment by artsmc** [comment]
Awesome I'll be conducting some new test and updating the documentation today.We have a blizzard outside in DC right now, so I got nothing but time. @stefanneculai I think this will be the only WYSIWYG on a framework that allows you to add custom buttons.
