### ISSUE TITLE
"Open in new tab" setting is ignored when creating a new link from the popup (with no pre-existing link text) if htmlAllowedAttrs or htmlAllowedTags params are present

### ISSUE THREAD

**Issue by BillyRayPreachersSon** [froala/ember-froala#23]
**Steps to reproduce**
1. Go to a page containing an Ember form with the Froala RTE on. Ensure that either the htmlAllowedAttrs or htmlAllowedTags params are being set (see below for the values I'm assigning to these params)
2. Click in the Froala RTE
3. Without typing or selecting any text, click the link button in the toolbar
4. Type in a URL (I used "http://www.google.co.uk/")
5. Type in link text (I used "Google")
6. Check the "Open in new tab" checkbox
7. Click "Insert"

**Expected result**
The markup will be as follows:

```
<p><a href="http://www.google.co.uk/" target="_blank">Google</a></p>
```

**Actual result**
The markup is missing the "target" attribute, and is as follows:

```
<p><a href="http://www.google.co.uk/">Google</a></p>
```

**Other information**
I've tried this with ember-froala v2.1.0 and v2.2.4, and the issue is present in both.

Our Froala editor params are as follows:

```
froalaEditor: {
    params: {
        key: 'our key here',
        htmlAllowedAttrs: ['href', 'target'],
        htmlAllowedTags: ['b', 'strong', 'i', 'p', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'li', 'a']
    }
}
```

If I remove both of the "htmlAllowedAttrs" and "htmlAllowedTags" params, the issue goes away. With either of those present, the issue comes back.

What is also odd is that if I create a link by selecting pre-existing link text **before** clicking the link button in the toolbar, the issue doesn't happen - even with those params present.

**Comment by stefanneculai** [comment]
Could you please make a jsFiddle? Thank you.

**Comment by BillyRayPreachersSon** [comment]
I've tried using both JSFiddle and CodePen, but neither seem to want to play ball with Ember.

If you use the above code, does it work for you?

**Comment by stefanneculai** [comment]
Is it happening in a blank editor instance without Ember?

**Comment by Panman82** [comment]
Couple thoughts; have you updated your `bower.json` dep for "froala-wysiwyg-editor"? While they are the same version, each have their own purpose.

What you are describing would be more of a Froala Editor issue specifically and not with the Ember addon. Therefore, you could make a JSFiddle without Ember and still reproduce the problem.

Edit: Here is a "base" JS Fiddle example; https://jsfiddle.net/Panman8201/4jxr3mfx/ Be sure to add [plugins from the CDN](https://cdnjs.com/libraries/froala-editor) that you may use, along with setting the proper options.

**Comment by BillyRayPreachersSon** [comment]
Hmm - I've managed to get Froala up and running in JSFiddle without Ember, but for the life of me, I can't seem to get the "insert link" toolbar button up and running.

Does anyone see where I'm going wrong?

https://jsfiddle.net/CodeCouch/bvrsrhb7/

Thanks... I had hoped that I'd provided enough information in the bug report for others to reproduce this... as you can see, I'm having trouble doing so on a publicly-accessible URL!

**Comment by Panman82** [comment]
Not sure what was up with your Fiddle, but take a look at this one: https://jsfiddle.net/Panman8201/4jxr3mfx/4/ 

Edit: Updated the Fiddle to include the [HTML] button to view the code produced.

**Comment by BillyRayPreachersSon** [comment]
Aah nice, I've updated it to have a console.log, which shows the problem as described above perfectly:  https://jsfiddle.net/CodeCouch/4jxr3mfx/5/

So it looks like the problem is with Froala, not the Froala Ember add-on.

@stefanneculai : Would you like me to report this via the Froala "Contact" page, or will this issue be enough?
