### ISSUE TITLE
Examples on how to use without closure actions?

### ISSUE THREAD

**Issue by danlourenco** [froala/ember-froala#24]
Hi there,

We're planning on upgrading to Ember 1.13 in the near future, but for now I'm trying to get ember-froala to work with our application at 1.12.  Are there any examples of how we'd use this without closure actions?  For instance, how would we go about wiring up the contentChanged event?

Cheers

**Comment by artsmc** [comment]
@dlo83 I'll look into this but as of now, I don't think it's possible. One of the limitations with 
Ember <1.12 is that we could not retrieve a callback on the actions. 
I have a project on 1.12 that I can do some testing with, but you may have to upgrade and use the legacy-addons http://emberjs.com/deprecations/v2.x/#toc_legacy-support-addons

**Comment by danlourenco** [comment]
@artsmc Thanks for the heads up!
