### ISSUE TITLE
Depreciate this addon in favor of ember-froala-editor

### ISSUE THREAD

**Issue by Panman82** [froala/ember-froala#28]
Its been a year since there has been active development with this addon. I've been keeping the [other "official" Froala editor Ember addon](https://github.com/froala/ember-froala-editor) updated as changes are needed. The existence of both has caused some confusion on which to use. And looking at the [npm download stats](https://npm-stat.com/charts.html?package=ember-froala&package=ember-froala-editor&from=2016-01-27&to=2017-01-27), the other has recently over-taken the lead. I'd suggest we do a few things;

- [ ] `npm deprecate ember-froala "ember-froala has been deprecated in favor of ember-froala-editor"`
- [x] Add a note towards the top of the README about the deprecation
- [ ] Publish one more version once Froala Editor 2.4.3 is out, so that the README makes it to [npm](https://www.npmjs.com/package/ember-froala) and [Ember Observer](https://www.emberobserver.com/addons/ember-froala)
- [x] Close existing PR's

Any thoughts / objections? I don't want to cause any hard feelings towards the original addon authors, just want to help clear up any confusion in the ember community/ecosystem.

**Comment by artsmc** [comment]
Nope I figured that was always the plan once the numbers supported it.

**Comment by stefanneculai** [comment]
Done.

**Comment by Panman82** [comment]
Re-opening as the README update didn't make it to Ember Observer (changed after version 2.4.2 released).

@stefanneculai we'll need to have one more release once 2.4.3 is out.

Can one of you run the npm deprecate command? I don't have rights to publish ember-froala on npm.
`npm deprecate ember-froala "ember-froala has been deprecated in favor of ember-froala-editor"`

**Comment by Panman82** [comment]
@stefanneculai or @artsmc can one of you publish 2.5.0 and run the deprecate command mentioned above? Then I think we're done here. :)

**Comment by stefanneculai** [comment]
Should be fine now. Thanks for the reminder @Panman8201
