### ISSUE TITLE
How can i attach nested events to editor?

### ISSUE THREAD

**Issue by jerichozis** [froala/ember-froala#6]
Im getting trouble with binding an image.uploaded event.
 {{froala-editor  image.uploaded = (action 'imageUploaded')}} - not working,it doesnt support dot syntax in template.

but it exists in eventNames,anyway.

**Comment by stefanneculai** [comment]
@maulsea do you have any thoughts about this one?

**Comment by artsmc** [comment]
@jerichozis  I think this is a deeper issue. Unless we are passing a value as a positional param no param with a separator will work. 
Looking at the EventsName this may need to be mapped a little different to account for that so you would pass imageUploaded= vs. image.uploaded=
I submitted a pull request to fix this issue. Basically you would have to use key value pairs to account for the nested events.

**Comment by jerichozis** [comment]
@artsmc thanks.

**Comment by artsmc** [comment]
no problem they have not merged it yet but I'm sure it would be easier to use my fork for now...
https://github.com/artsmc/ember-froala
I also updated the documentation to include a few other things.

**Comment by stefanneculai** [comment]
Done #9
