### ISSUE TITLE
Uncaught TypeError: this.$(...).editable is not a function

### ISSUE THREAD

**Issue by 20v100** [froala/ember-froala#7]
I got the error: Uncaught TypeError: this.$(...).editable is not a function. At line 21 of the froala-editor component.js. First time I try to use this addon. I tried to replicate the exact implementation suggested on this repository. I run:
Ember      : 2.1.0
Ember Data : 2.1.0
Firebase   : 2.3.1
EmberFire  : 1.6.0
jQuery     : 1.11.3

Not sure how to resolve this.

**Comment by 20v100** [comment]
Update: Froala was upgraded to 2.0 on Nov 16. `.editable()` has been deprecated in favor of `.froalaEditor()`

**Comment by stefanneculai** [comment]
That is right, Vincent, We're doing some update to this right now.
