### ISSUE TITLE
Using the Save Button Concept

### ISSUE THREAD

**Issue by artsmc** [froala/ember-froala#8]
https://www.froala.com/wysiwyg-editor/docs/concepts/save-button
I am unable to run the save.save on a button outside of the editor
Perhaps you can add:
{{#froala-editor}}
custom html inside to access editor
{{/froala-editor}}

**Comment by artsmc** [comment]
Figured out how to use the save concept 
actions: {
        saveStuff: function(){
            console.log("Content Saved");
//using the the component name directly gives me access to the editor function but you should add ClassName 'froalaEditor' to the component to make it easier to access
            $('div#ember632').froalaEditor('save.save');
        },
        contentChanged: function(event, editor) {
          console.log("Content Changed");
          //console.log(event);
          //console.log(editor);
        },
        focus: function(event, editor) {
          //console.log("Focus");
          //console.log(event);
          //console.log(editor);
        },
    },

**Comment by stefanneculai** [comment]
:+1: Could you add this in ReadME and make a PR?
